print("Who am I?")


print("I am Aarav")
print("I am 10 years old")
print("I am a student")
print("I love playing soccer")
print("I love math")
print("I like to read books")
print("I have a pet dog named Max")
print("I am in 4th grade")
print("I am from India")
print("I have a big family with 3 siblings")
print("I enjoy spending time with my friends and family")
print("I am a kind and caring person")
print("I am always eager to learn new things espiecally in math and technology")
print("I am proud of my culture and heritage")
print("I am excited about the future and all the opportunities it holds for me")
print("I am grateful for the love and support of my family and friends")
print("I am Aarav, and this is who I am!")